[general]
import = [
    "https://raw.githubusercontent.com/alacritty/alacritty-theme/refs/heads/master/themes/kitty.toml"
]

[font]
size = 12

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"
